// SPDX-License-Identifier: Apache-2.0
package de.diamaneos.downloads;

import java.net.MalformedURLException;
import java.net.URL;

/** A closed policy vocabulary. No caller or stored value supplies a URL. */
public final class DownloadPolicy {
    public static final int VERSION = 1;
    public static final String PRIMARY = "primary_eu";
    public static final String CANADA = "canada";
    public static final DownloadPolicy DEFAULT = new DownloadPolicy(PRIMARY, false);
    public final String server;
    public final boolean fallback;

    private DownloadPolicy(String server, boolean fallback) {
        this.server = server;
        this.fallback = fallback;
    }

    public static DownloadPolicy require(Object version, Object server, Object fallback) {
        if (!(version instanceof Integer) || (Integer) version != VERSION
                || !(fallback instanceof Boolean)
                || !(PRIMARY.equals(server) || CANADA.equals(server))) {
            throw new IllegalArgumentException("Unknown download policy");
        }
        return new DownloadPolicy((String) server, (Boolean) fallback);
    }

    public String encode() {
        return VERSION + ":" + server + ":" + (fallback ? "1" : "0");
    }

    public static DownloadPolicy decode(String value) {
        if (value == null || value.length() > 32) return DEFAULT;
        for (String server : new String[]{PRIMARY, CANADA}) {
            for (boolean fallback : new boolean[]{false, true}) {
                DownloadPolicy p = new DownloadPolicy(server, fallback);
                if (p.encode().equals(value)) return p;
            }
        }
        return DEFAULT;
    }

    public URL url(boolean apps, String path, boolean alternate) throws MalformedURLException {
        if (path == null || !path.matches("[A-Za-z0-9][A-Za-z0-9_./-]{0,511}")) {
            throw new MalformedURLException("Invalid download path");
        }
        for (String part : path.split("/", -1)) {
            if (part.isEmpty() || part.equals(".") || part.equals("..")) {
                throw new MalformedURLException("Invalid download path");
            }
        }
        if (alternate && !fallback) throw new MalformedURLException("Fallback is disabled");
        boolean canada = CANADA.equals(server) != alternate;
        String host = apps ? "apps" : "releases";
        return new URL("https://" + host + (canada ? "-na" : "") + ".diamaneos.de/" + path);
    }

    /** Only canonical Apps URLs generated by this client may enter the HTTP adapter. */
    public static String appsPath(String value) throws MalformedURLException {
        for (String base : new String[]{"https://apps.diamaneos.de/", "https://apps-na.diamaneos.de/"}) {
            if (value != null && value.startsWith(base)) {
                String path = value.substring(base.length());
                DEFAULT.url(true, path, false);
                return path;
            }
        }
        throw new MalformedURLException("Unapproved Apps origin");
    }
}
